/**
 * Bundles the plugin UI (src/ui) into src/mcp/ui.generated.ts so the worker can
 * serve it as a single self-contained HTML resource. Run: bun run build:ui
 */
const root = new URL("..", import.meta.url).pathname;

const result = await Bun.build({
  entrypoints: [`${root}src/ui/app.ts`],
  target: "browser",
  format: "esm",
  minify: true,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
const js = await result.outputs[0].text();

const minifyCss = (css: string) => css.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\s+/g, " ").replace(/\s*([{}:;,>])\s*/g, "$1").replace(/;}/g, "}").trim();
const hostCss = await Bun.file(`${root}node_modules/@openai/mcp-extensions/styles.css`).text();
const appCss = await Bun.file(`${root}src/ui/app.css`).text();
const css = minifyCss(`${hostCss}\n${appCss}`).replace(/<\/style/gi, "<\\/style");

const out = `// Generated by scripts/build-ui.ts. Do not edit.
export const NESTLING_UI_JS = ${JSON.stringify(js)};
export const NESTLING_UI_CSS = ${JSON.stringify(css)};
`;
await Bun.write(`${root}src/mcp/ui.generated.ts`, out);
console.log(`UI bundle: ${(js.length / 1024).toFixed(1)} KB JS, ${(css.length / 1024).toFixed(1)} KB CSS`);
